Repository codesquad-member-2020/baseball-04, pull requests merged in 2020-05, with the labels that each got.

#5 [iOS] 개발환경 세팅
  iOS/BaseBallGame/BaseBallGame.xcodeproj/project.pbxproj
  iOS/BaseBallGame/BaseBallGame/Base.lproj/Main.storyboard
  iOS/BaseBallGame/BaseBallGame/RectView.swift
  iOS/BaseBallGame/BaseBallGame/ViewController.swift
Labels: iOS

#19 [FE] 개발환경 구축
  README.md
  fe/.env
  fe/.gitignore
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.js
  fe/src/App.test.js
  fe/src/index.css
  fe/src/index.js
  fe/src/serviceWorker.js
  fe/src/setupTests.js
  fe/tmp
Labels: FE

#24 [FE] 게임 첫 화면 UI 구현
  fe/src/App.js
  fe/src/components/GameList.jsx
  fe/src/components/Main.jsx
  fe/src/index.js
Labels: FE

#25 [FE] 리액트 라우팅 기능 구현
  fe/package-lock.json
  fe/package.json
  fe/src/App.js
  fe/src/components/Game.jsx
  fe/src/components/GameList.jsx
  fe/src/components/Main.jsx
Labels: FE

#27 게임 목록 화면 구현
  iOS/BaseBallGame/BaseBallGame.xcodeproj/project.pbxproj
  iOS/BaseBallGame/BaseBallGame/Assets.xcassets/BabyPink.colorset/Contents.json
  iOS/BaseBallGame/BaseBallGame/Assets.xcassets/DarkDeepPurple.colorset/Contents.json
  iOS/BaseBallGame/BaseBallGame/Assets.xcassets/DeepRed.colorset/Contents.json
  iOS/BaseBallGame/BaseBallGame/Assets.xcassets/Raseberry.colorset/Contents.json
  iOS/BaseBallGame/BaseBallGame/Assets.xcassets/baseballBall.imageset/Contents.json
  iOS/BaseBallGame/BaseBallGame/Assets.xcassets/baseballBall.imageset/icons8-baseball-ball-90.png
  iOS/BaseBallGame/BaseBallGame/Assets.xcassets/baseballBet.imageset/Contents.json
  iOS/BaseBallGame/BaseBallGame/Assets.xcassets/baseballBet.imageset/icons8-baseball-100.png
  iOS/BaseBallGame/BaseBallGame/Assets.xcassets/baseballLetter.imageset/Contents.json
  iOS/BaseBallGame/BaseBallGame/Assets.xcassets/baseballLetter.imageset/baseball-2242378_1280.png
  iOS/BaseBallGame/BaseBallGame/Assets.xcassets/baseballPlayer.imageset/Contents.json
  iOS/BaseBallGame/BaseBallGame/Assets.xcassets/baseballPlayer.imageset/icons8-baseball-player-90.png
  iOS/BaseBallGame/BaseBallGame/Assets.xcassets/softballMitt.imageset/Contents.json
  iOS/BaseBallGame/BaseBallGame/Assets.xcassets/softballMitt.imageset/icons8-softball-mitt-100.png
  iOS/BaseBallGame/BaseBallGame/Base.lproj/Main.storyboard
  iOS/BaseBallGame/BaseBallGame/Controller/GameListViewController.swift
  iOS/BaseBallGame/BaseBallGame/Controller/GameViewController.swift
  iOS/BaseBallGame/BaseBallGame/Controller/LoginViewController.swift
  iOS/BaseBallGame/BaseBallGame/Controller/ScoreDetailViewController.swift
  iOS/BaseBallGame/BaseBallGame/Model/BaseBallGameInfo.swift
  iOS/BaseBallGame/BaseBallGame/View/Game.swift
  iOS/BaseBallGame/BaseBallGame/View/GameStackCell.xib
  iOS/BaseBallGame/BaseBallGame/View/GameStackView.swift
Labels: iOS

#28 [FE] 게임 진행화면 UI 구현
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/robots.txt
  fe/src/App.js
  fe/src/components/Game.jsx
  fe/src/components/Game/BattingLog.jsx
  fe/src/components/Game/Field.jsx
  fe/src/components/Game/Game.jsx
  fe/src/components/Game/PlayerInfo.jsx
  fe/src/components/Game/TeamScore.jsx
  fe/src/components/GameList.jsx
  fe/src/components/Main.jsx
  fe/src/images/diamond2.png
  fe/src/images/stadium.jpg
  fe/src/images/전광판.png
  fe/src/index.css
Labels: FE

#29 [FE] 상세점수 화면, 선수명단 화면 구현
  fe/src/App.js
  fe/src/components/Game/BattingLog.jsx
  fe/src/components/Game/Field.jsx
  fe/src/components/Game/Game.jsx
  fe/src/components/Game/TeamScore.jsx
  fe/src/components/Popup.jsx
Labels: FE

#30 [FE] UI 추가 기능 구현
  fe/src/App.js
  fe/src/components/Game/BattingLog.jsx
  fe/src/components/Game/Field.jsx
  fe/src/components/Game/Game.jsx
  fe/src/components/Game/PlayerInfo.jsx
  fe/src/components/Game/TeamScore.jsx
  fe/src/components/Popup.jsx
Labels: FE

#33 [FE] 애니메이션 구현
  fe/src/components/Game/Field.jsx
  fe/src/components/Main.jsx
Labels: FE

#34 [FE] 피드백 받은 코드 리팩토링
  fe/src/components/Game/Field.jsx
  fe/src/components/Game/PitchBtn.jsx
  fe/src/components/Main.jsx
Labels: FE

#44 [FE] 서버로부터 받은 데이터 상태관리
  fe/src/App.js
  fe/src/Store.jsx
  fe/src/components/Game/BattingLog.jsx
  fe/src/components/Game/Field.jsx
  fe/src/components/Game/Game.jsx
  fe/src/components/Game/PitchBtn.jsx
  fe/src/components/Game/PlayerInfo.jsx
  fe/src/components/Game/TeamScore.jsx
  fe/src/components/GameList.jsx
  fe/src/components/Main.jsx
  fe/src/components/Popup.jsx
Labels: FE

#47 [BE] OAuth 2.0 GitHub 로그인 기능 구현
  be/src/main/java/io/codesquad/baseball/auth/AuthController.java
  be/src/main/java/io/codesquad/baseball/system/WebMvcConfig.java
  be/src/main/resources/application.properties
  be/src/main/resources/schema.sql
Labels: BE
